#!/bin/tcsh -f
set texname=$1
set imgname=$2
set dpi=$3

if ( $dpi == "0" ) then
  cp Figures-png/"$imgname".png Figures/"$imgname".eps
  exit
endif

set h=`grep -h includegraphics *.tex | grep "{$imgname}" | grep height | sed -e 's/.*height=\([0-9]*\)mm\]{\(.*\)}.*/\1/g' | awk '{ print int(($1/25.4)*'$dpi') }'`
set w=`grep -h includegraphics *.tex | grep "{$imgname}" | grep width | sed -e 's/.*width=\([0-9]*\)mm\]{\(.*\)}.*/\1/g' | awk '{ print int(($1/25.4)*'$dpi') }'`

echo === texname=$texname imgname=$imgname dpi=$dpi h=$h w=$w

if ( $h != "" ) then
  echo =   HEIGHT resampling to $h pixels: Figures-png/$imgname.png 
  pngtopnm Figures-png/"$imgname".png | pnmscale -ysize=$h | pnmtopng > Figures/"$imgname".png
else
  echo =   WIDTH resampling to $h pixels: Figures-png/$imgname.png 
  pngtopnm Figures-png/"$imgname".png | pnmscale -xsize=$w | pnmtopng > Figures/"$imgname".png
endif

